from __future__ import annotations

import argparse
from pathlib import Path

from llm_logparser.core.embedding_backend import SUPPORTED_EMBEDDING_BACKENDS
from llm_logparser.core.i18n import _


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="llm-logparser",
        description=_("cli.description"),
    )
    parser.add_argument(
        "--locale",
        "--lang",
        dest="locale",
        default=None,
        help=_("cli.option.lang.help"),
    )
    parser.add_argument(
        "--log-level",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        default=None,
        help=_("cli.option.log_level.help"),
    )
    parser.add_argument("--config", type=Path, help=_("cli.option.config.help"))
    parser.add_argument("--profile", help=_("cli.option.profile.help"))
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help=_("cli.option.non_interactive.help"),
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    parse_cmd = subparsers.add_parser(
        "parse",
        help=_("cli.parse.help"),
    )
    parse_cmd.add_argument(
        "--provider",
        required=False,
        help=_("cli.parse.opt.provider.help"),
    )
    parse_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.parse.opt.input.help"),
    )
    parse_cmd.add_argument(
        "--outdir",
        required=False,
        type=Path,
        default=Path("artifacts"),
        help=_("cli.parse.opt.outdir.help"),
    )
    parse_cmd.add_argument(
        "--dry-run",
        dest="dry_run",
        action="store_true",
        help=_("cli.parse.opt.dry_run.help"),
    )
    parse_cmd.add_argument(
        "--fail-fast",
        dest="fail_fast",
        action="store_true",
        help=_("cli.parse.opt.fail_fast.help"),
    )
    parse_cmd.add_argument(
        "--validate-schema",
        dest="validate_schema",
        action="store_true",
        help=_("cli.parse.opt.validate_schema.help"),
    )
    parse_cmd.add_argument(
        "--message-window-size",
        dest="message_window_size",
        type=int,
        default=4,
        help=_("cli.parse.opt.message_window_size.help"),
    )
    parse_cmd.add_argument(
        "--message-window-stride",
        dest="message_window_stride",
        type=int,
        default=None,
        help=_("cli.parse.opt.message_window_stride.help"),
    )

    export_cmd = subparsers.add_parser(
        "export",
        help=_("cli.export.help"),
    )
    export_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.export.opt.input.help"),
    )
    export_cmd.add_argument(
        "--out",
        required=False,
        type=Path,
        help=_("cli.export.opt.out.help"),
    )
    export_cmd.add_argument(
        "--timezone",
        "--tz",
        dest="timezone",
        required=False,
        default="UTC",
        help=_("cli.option.timezone.help"),
    )
    export_cmd.add_argument(
        "--formatting",
        choices=["none", "light"],
        default="light",
        help=_("cli.option.formatting.help"),
    )
    export_cmd.add_argument("--split", dest="split", help=_("cli.option.split.help"))
    export_cmd.add_argument("--split-soft-overflow", dest="split_soft_overflow", type=float, default=0.20)
    export_cmd.add_argument("--split-hard", dest="split_hard", action="store_true")
    export_cmd.add_argument("--split-preview", dest="split_preview", action="store_true")
    export_cmd.add_argument(
        "--tiny-tail-threshold",
        dest="tiny_tail_threshold",
        type=int,
        default=20,
        help=_("cli.option.tiny_tail_threshold.help"),
    )

    extract_cmd = subparsers.add_parser(
        "extract",
        help=_("cli.extract.help"),
    )
    extract_cmd.add_argument(
        "--provider",
        required=False,
        help=_("cli.parse.opt.provider.help"),
    )
    extract_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.extract.opt.input.help"),
    )
    extract_cmd.add_argument(
        "--conversation-id",
        required=False,
        help=_("cli.extract.opt.conversation_id.help"),
    )
    extract_cmd.add_argument(
        "--outdir",
        required=False,
        type=Path,
        default=Path("artifacts"),
        help=_("cli.extract.opt.outdir.help"),
    )
    extract_cmd.add_argument(
        "--dry-run",
        dest="dry_run",
        action="store_true",
        help=_("cli.parse.opt.dry_run.help"),
    )

    analyze_cmd = subparsers.add_parser(
        "analyze",
        help=_("cli.analyze.help"),
    )
    analyze_subparsers = analyze_cmd.add_subparsers(
        dest="analyze_command",
        required=True,
    )
    analyze_stats_cmd = analyze_subparsers.add_parser(
        "stats",
        help=_("cli.analyze.stats.help"),
    )
    analyze_stats_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.opt.input.help"),
    )
    analyze_stats_cmd.add_argument(
        "--json",
        dest="json",
        action="store_true",
        help=_("cli.analyze.opt.json.help"),
    )
    analyze_stats_cmd.add_argument(
        "--out",
        required=False,
        type=Path,
        help=_("cli.analyze.opt.out.help"),
    )
    analyze_stats_cmd.add_argument(
        "--per-thread",
        dest="per_thread",
        action="store_true",
        help=_("cli.analyze.stats.opt.per_thread.help"),
    )
    analyze_stats_cmd.add_argument(
        "--top",
        required=False,
        type=int,
        help=_("cli.analyze.stats.opt.top.help"),
    )
    analyze_stats_cmd.add_argument(
        "--sort",
        choices=["messages", "chars", "span", "conversation_id"],
        default=None,
        help=_("cli.analyze.stats.opt.sort.help"),
    )
    analyze_stats_cmd.add_argument(
        "--include-role-breakdown",
        dest="include_role_breakdown",
        action="store_true",
        help=_("cli.analyze.stats.opt.include_role_breakdown.help"),
    )

    analyze_datasheet_cmd = analyze_subparsers.add_parser(
        "datasheet",
        help=_("cli.analyze.datasheet.help"),
    )
    analyze_datasheet_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.opt.input.help"),
    )
    analyze_datasheet_cmd.add_argument(
        "--json",
        dest="json",
        action="store_true",
        help=_("cli.analyze.opt.json.help"),
    )
    analyze_datasheet_cmd.add_argument(
        "--out",
        required=False,
        type=Path,
        help=_("cli.analyze.opt.out.help"),
    )

    analyze_timeline_cmd = analyze_subparsers.add_parser(
        "timeline",
        help=_("cli.analyze.timeline.help"),
    )
    analyze_timeline_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.opt.input.help"),
    )
    analyze_timeline_cmd.add_argument(
        "--bucket",
        choices=["hour", "day", "week", "month"],
        default="day",
        help=_("cli.analyze.timeline.opt.bucket.help"),
    )
    analyze_timeline_cmd.add_argument(
        "--json",
        dest="json",
        action="store_true",
        help=_("cli.analyze.opt.json.help"),
    )
    analyze_timeline_cmd.add_argument(
        "--out",
        required=False,
        type=Path,
        help=_("cli.analyze.opt.out.help"),
    )

    analyze_tokens_cmd = analyze_subparsers.add_parser(
        "tokens",
        help=_("cli.analyze.tokens.help"),
        description=_("cli.analyze.tokens.help"),
    )
    analyze_tokens_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.opt.input.help"),
    )
    analyze_tokens_cmd.add_argument(
        "--model",
        required=False,
        help=_("cli.analyze.tokens.opt.model.help"),
    )
    analyze_tokens_cmd.add_argument(
        "--encoding",
        required=False,
        help=_("cli.analyze.tokens.opt.encoding.help"),
    )
    analyze_tokens_cmd.add_argument(
        "--skip-existing",
        dest="skip_existing",
        action="store_true",
        help=_("cli.analyze.opt.skip_existing.help"),
    )
    analyze_tokens_cmd.add_argument(
        "--dry-run",
        dest="dry_run",
        action="store_true",
        help=_("cli.analyze.opt.dry_run.help"),
    )

    analyze_metrics_cmd = analyze_subparsers.add_parser(
        "metrics",
        help=_("cli.analyze.metrics.help"),
        description=_("cli.analyze.metrics.help"),
    )
    analyze_metrics_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.opt.input.help"),
    )
    analyze_metrics_cmd.add_argument(
        "--skip-existing",
        dest="skip_existing",
        action="store_true",
        help=_("cli.analyze.opt.skip_existing.help"),
    )
    analyze_metrics_cmd.add_argument(
        "--dry-run",
        dest="dry_run",
        action="store_true",
        help=_("cli.analyze.opt.dry_run.help"),
    )

    analyze_token_dictionary_cmd = analyze_subparsers.add_parser(
        "token-dictionary",
        help=_("cli.analyze.token_dictionary.help"),
        description=_("cli.analyze.token_dictionary.help"),
    )
    analyze_token_dictionary_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.token_dictionary.opt.input.help"),
    )
    analyze_token_dictionary_cmd.add_argument(
        "--overwrite",
        dest="overwrite",
        action="store_true",
        help=_("cli.analyze.token_dictionary.opt.overwrite.help"),
    )
    analyze_token_dictionary_cmd.add_argument(
        "--skip-existing",
        dest="skip_existing",
        action="store_true",
        help=_("cli.analyze.opt.skip_existing.help"),
    )
    analyze_token_dictionary_cmd.add_argument(
        "--dry-run",
        dest="dry_run",
        action="store_true",
        help=_("cli.analyze.opt.dry_run.help"),
    )

    analyze_lexical_rule_candidates_cmd = analyze_subparsers.add_parser(
        "lexical-rule-candidates",
        help=_("cli.analyze.lexical_rule_candidates.help"),
        description=_("cli.analyze.lexical_rule_candidates.help"),
    )
    analyze_lexical_rule_candidates_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.lexical_rule_candidates.opt.input.help"),
    )
    analyze_lexical_rule_candidates_cmd.add_argument(
        "--project-lexical-rules",
        dest="project_lexical_rules",
        type=Path,
        default=None,
        help=_("cli.analyze.lexical_rule_candidates.opt.project_lexical_rules.help"),
    )
    analyze_lexical_rule_candidates_cmd.add_argument(
        "--user-lexical-rules",
        dest="user_lexical_rules",
        type=Path,
        default=None,
        help=_("cli.analyze.lexical_rule_candidates.opt.user_lexical_rules.help"),
    )
    analyze_lexical_rule_candidates_cmd.add_argument(
        "--max-candidates-per-type",
        dest="max_candidates_per_type",
        type=int,
        default=100,
        help=_("cli.analyze.lexical_rule_candidates.opt.max_candidates_per_type.help"),
    )
    analyze_lexical_rule_candidates_cmd.add_argument(
        "--sample-limit",
        dest="sample_limit",
        type=int,
        default=5,
        help=_("cli.analyze.lexical_rule_candidates.opt.sample_limit.help"),
    )
    analyze_lexical_rule_candidates_cmd.add_argument(
        "--overwrite",
        dest="overwrite",
        action="store_true",
        help=_("cli.analyze.lexical_rule_candidates.opt.overwrite.help"),
    )

    analyze_sqlite_build_cmd = analyze_subparsers.add_parser(
        "sqlite-build",
        help=_("cli.analyze.sqlite_build.help"),
    )
    analyze_sqlite_build_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.sqlite_build.opt.input.help"),
    )
    analyze_sqlite_build_cmd.add_argument(
        "--provider",
        required=False,
        help=_("cli.analyze.sqlite_build.opt.provider.help"),
    )
    analyze_sqlite_build_cmd.add_argument(
        "--overwrite",
        dest="overwrite",
        action="store_true",
        help=_("cli.analyze.sqlite_build.opt.overwrite.help"),
    )

    analyze_semantic_prototype_cmd = analyze_subparsers.add_parser(
        "semantic-prototype",
        help=_("cli.analyze.semantic_prototype.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.semantic_prototype.opt.input.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--backend",
        choices=list(SUPPORTED_EMBEDDING_BACKENDS),
        default="deterministic-hash",
        help=_("cli.analyze.semantic_prototype.opt.backend.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--model",
        required=False,
        help=_("cli.analyze.semantic_prototype.opt.model.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--top-k",
        dest="top_k",
        type=int,
        default=5,
        help=_("cli.analyze.semantic_prototype.opt.top_k.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--min-score",
        dest="min_score",
        type=float,
        default=0.62,
        help=_("cli.analyze.semantic_prototype.opt.min_score.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--max-input-bytes",
        dest="max_input_bytes",
        type=int,
        help=_("cli.analyze.semantic_prototype.opt.max_input_bytes.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--chunk-overlap-bytes",
        dest="chunk_overlap_bytes",
        type=int,
        help=_("cli.analyze.semantic_prototype.opt.chunk_overlap_bytes.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--aggregate",
        choices=["mean"],
        help=_("cli.analyze.semantic_prototype.opt.aggregate.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--sqlite-db",
        dest="sqlite_db",
        type=Path,
        help=_("cli.analyze.semantic_prototype.opt.sqlite_db.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--candidate-window-days",
        dest="candidate_window_days",
        type=int,
        default=30,
        help=_("cli.analyze.semantic_prototype.opt.candidate_window_days.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--candidate-min-chars",
        dest="candidate_min_chars",
        type=int,
        default=0,
        help=_("cli.analyze.semantic_prototype.opt.candidate_min_chars.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--candidate-min-assistant-ratio",
        dest="candidate_min_assistant_ratio",
        type=float,
        default=0.0,
        help=_("cli.analyze.semantic_prototype.opt.candidate_min_assistant_ratio.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--candidate-same-thread",
        dest="candidate_same_thread",
        choices=["allow", "prefer", "only", "exclude"],
        default="allow",
        help=_("cli.analyze.semantic_prototype.opt.candidate_same_thread.help"),
    )
    analyze_semantic_prototype_cmd.add_argument(
        "--overwrite",
        dest="overwrite",
        action="store_true",
        help=_("cli.analyze.semantic_prototype.opt.overwrite.help"),
    )

    analyze_intra_thread_topics_cmd = analyze_subparsers.add_parser(
        "intra-thread-topics",
        help=_("cli.analyze.intra_thread_topics.help"),
    )
    analyze_intra_thread_topics_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.intra_thread_topics.opt.input.help"),
    )
    analyze_intra_thread_topics_cmd.add_argument(
        "--backend",
        choices=list(SUPPORTED_EMBEDDING_BACKENDS),
        default="deterministic-hash",
        help=_("cli.analyze.intra_thread_topics.opt.backend.help"),
    )
    analyze_intra_thread_topics_cmd.add_argument(
        "--model",
        required=False,
        help=_("cli.analyze.intra_thread_topics.opt.model.help"),
    )
    analyze_intra_thread_topics_cmd.add_argument(
        "--window-size",
        dest="window_size",
        type=int,
        default=3,
        help=_("cli.analyze.intra_thread_topics.opt.window_size.help"),
    )
    analyze_intra_thread_topics_cmd.add_argument(
        "--window-stride",
        dest="window_stride",
        type=int,
        default=1,
        help=_("cli.analyze.intra_thread_topics.opt.window_stride.help"),
    )
    analyze_intra_thread_topics_cmd.add_argument(
        "--boundary-threshold",
        dest="boundary_threshold",
        type=float,
        default=0.75,
        help=_("cli.analyze.intra_thread_topics.opt.boundary_threshold.help"),
    )
    analyze_intra_thread_topics_cmd.add_argument(
        "--max-input-bytes",
        dest="max_input_bytes",
        type=int,
        help=_("cli.analyze.intra_thread_topics.opt.max_input_bytes.help"),
    )
    analyze_intra_thread_topics_cmd.add_argument(
        "--chunk-overlap-bytes",
        dest="chunk_overlap_bytes",
        type=int,
        help=_("cli.analyze.intra_thread_topics.opt.chunk_overlap_bytes.help"),
    )
    analyze_intra_thread_topics_cmd.add_argument(
        "--aggregate",
        choices=["mean"],
        help=_("cli.analyze.intra_thread_topics.opt.aggregate.help"),
    )
    analyze_intra_thread_topics_cmd.add_argument(
        "--overwrite",
        dest="overwrite",
        action="store_true",
        help=_("cli.analyze.intra_thread_topics.opt.overwrite.help"),
    )
    analyze_intra_thread_topics_cmd.add_argument(
        "--report",
        dest="report",
        action="store_true",
        help=_("cli.analyze.intra_thread_topics.opt.report.help"),
    )
    analyze_intra_thread_topics_cmd.add_argument(
        "--merge-segments",
        dest="merge_segments",
        action="store_true",
        help=_("cli.analyze.intra_thread_topics.opt.merge_segments.help"),
    )

    analyze_intra_thread_topic_summaries_cmd = analyze_subparsers.add_parser(
        "intra-thread-topic-summaries",
        help=_("cli.analyze.intra_thread_topic_summaries.help"),
    )
    analyze_intra_thread_topic_summaries_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.intra_thread_topic_summaries.opt.input.help"),
    )
    analyze_intra_thread_topic_summaries_cmd.add_argument(
        "--source",
        choices=["heuristic", "local-llm"],
        default="heuristic",
        help=_("cli.analyze.intra_thread_topic_summaries.opt.source.help"),
    )
    analyze_intra_thread_topic_summaries_cmd.add_argument(
        "--model",
        required=False,
        default=None,
        help=_("cli.analyze.intra_thread_topic_summaries.opt.model.help"),
    )
    analyze_intra_thread_topic_summaries_cmd.add_argument(
        "--base-url",
        dest="base_url",
        default="http://localhost:11434",
        help=_("cli.analyze.intra_thread_topic_summaries.opt.base_url.help"),
    )
    analyze_intra_thread_topic_summaries_cmd.add_argument(
        "--timeout-seconds",
        dest="timeout_seconds",
        type=float,
        default=120.0,
        help=_("cli.analyze.intra_thread_topic_summaries.opt.timeout_seconds.help"),
    )
    analyze_intra_thread_topic_summaries_cmd.add_argument(
        "--jobs",
        dest="jobs",
        type=int,
        default=1,
        help=_("cli.analyze.intra_thread_topic_summaries.opt.jobs.help"),
    )
    analyze_intra_thread_topic_summaries_cmd.add_argument(
        "--overwrite",
        dest="overwrite",
        action="store_true",
        help=_("cli.analyze.intra_thread_topic_summaries.opt.overwrite.help"),
    )

    analyze_semantic_preview_cmd = analyze_subparsers.add_parser(
        "semantic-preview",
        help=_("cli.analyze.semantic_preview.help"),
    )
    analyze_semantic_preview_cmd.add_argument(
        "--cluster-id",
        dest="cluster_id",
        help=_("cli.analyze.semantic_preview.opt.cluster_id.help"),
    )
    analyze_semantic_preview_cmd.add_argument(
        "--conversation-id",
        "--thread",
        dest="conversation_id",
        help=_("cli.analyze.semantic_preview.opt.conversation_id.help"),
    )
    analyze_semantic_preview_cmd.add_argument(
        "--window",
        dest="window_id",
        help=_("cli.analyze.semantic_preview.opt.window.help"),
    )
    analyze_semantic_preview_cmd.add_argument(
        "--top-clusters",
        dest="top_clusters",
        type=int,
        default=20,
        help=_("cli.analyze.semantic_preview.opt.top_clusters.help"),
    )
    analyze_semantic_preview_cmd.add_argument(
        "--min-cluster-size",
        dest="min_cluster_size",
        type=int,
        default=1,
        help=_("cli.analyze.semantic_preview.opt.min_cluster_size.help"),
    )
    analyze_semantic_preview_cmd.add_argument(
        "--cross-thread-only",
        dest="cross_thread_only",
        action="store_true",
        help=_("cli.analyze.semantic_preview.opt.cross_thread_only.help"),
    )
    analyze_semantic_preview_cmd.add_argument(
        "--json",
        dest="json_output",
        action="store_true",
        help=_("cli.analyze.semantic_preview.opt.json.help"),
    )
    analyze_semantic_preview_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.semantic_preview.opt.input.help"),
    )
    analyze_semantic_preview_cmd.add_argument(
        "--top-k",
        dest="top_k",
        type=int,
        help=_("cli.analyze.semantic_preview.opt.top_k.help"),
    )
    analyze_semantic_preview_cmd.add_argument(
        "--include-text",
        dest="include_text",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=_("cli.analyze.semantic_preview.opt.include_text.help"),
    )
    analyze_semantic_preview_cmd.add_argument(
        "--max-chars",
        dest="max_chars",
        type=int,
        default=400,
        help=_("cli.analyze.semantic_preview.opt.max_chars.help"),
    )
    analyze_semantic_preview_cmd.add_argument(
        "--show-meta",
        dest="show_meta",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=_("cli.analyze.semantic_preview.opt.show_meta.help"),
    )

    analyze_semantic_span_proposals_cmd = analyze_subparsers.add_parser(
        "semantic-span-proposals",
        help=_("cli.analyze.semantic_span_proposals.help"),
        description=_("cli.analyze.semantic_span_proposals.help"),
    )
    analyze_semantic_span_proposals_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.semantic_span_proposals.opt.input.help"),
    )

    analyze_cross_thread_candidates_cmd = analyze_subparsers.add_parser(
        "cross-thread-candidates",
        help=_("cli.analyze.cross_thread_candidates.help"),
    )
    analyze_cross_thread_candidates_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.cross_thread_candidates.opt.input.help"),
    )
    analyze_cross_thread_candidates_cmd.add_argument(
        "--min-score",
        dest="min_score",
        type=float,
        default=0.6,
        help=_("cli.analyze.cross_thread_candidates.opt.min_score.help"),
    )
    analyze_cross_thread_candidates_cmd.add_argument(
        "--top-per-source",
        dest="top_per_source",
        type=int,
        default=3,
        help=_("cli.analyze.cross_thread_candidates.opt.top_per_source.help"),
    )
    analyze_cross_thread_candidates_cmd.add_argument(
        "--unit-source",
        dest="unit_source",
        choices=("semantic-topics", "topic-summaries", "auto"),
        default="semantic-topics",
        help=_("cli.analyze.cross_thread_candidates.opt.unit_source.help"),
    )
    analyze_cross_thread_candidates_cmd.add_argument(
        "--embedding-model",
        dest="embedding_model",
        default=None,
        help=_("cli.analyze.cross_thread_candidates.opt.embedding_model.help"),
    )
    analyze_cross_thread_candidates_cmd.add_argument(
        "--embedding-base-url",
        dest="embedding_base_url",
        default="http://localhost:11434",
        help=_("cli.analyze.cross_thread_candidates.opt.embedding_base_url.help"),
    )
    analyze_cross_thread_candidates_cmd.add_argument(
        "--embedding-timeout-seconds",
        dest="embedding_timeout_seconds",
        type=float,
        default=30.0,
        help=_("cli.analyze.cross_thread_candidates.opt.embedding_timeout_seconds.help"),
    )
    analyze_cross_thread_candidates_cmd.add_argument(
        "--project-lexical-rules",
        dest="project_lexical_rules",
        type=Path,
        default=None,
        help=_("cli.analyze.cross_thread_candidates.opt.project_lexical_rules.help"),
    )
    analyze_cross_thread_candidates_cmd.add_argument(
        "--user-lexical-rules",
        dest="user_lexical_rules",
        type=Path,
        default=None,
        help=_("cli.analyze.cross_thread_candidates.opt.user_lexical_rules.help"),
    )

    analyze_cross_thread_intent_eval_cmd = analyze_subparsers.add_parser(
        "cross-thread-intent-eval",
        help=_("cli.analyze.cross_thread_intent_eval.help"),
    )
    analyze_cross_thread_intent_eval_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.cross_thread_intent_eval.opt.input.help"),
    )
    analyze_cross_thread_intent_eval_cmd.add_argument(
        "--model",
        required=True,
        help=_("cli.analyze.cross_thread_intent_eval.opt.model.help"),
    )
    analyze_cross_thread_intent_eval_cmd.add_argument(
        "--base-url",
        dest="base_url",
        default="http://localhost:11434",
        help=_("cli.analyze.cross_thread_intent_eval.opt.base_url.help"),
    )
    analyze_cross_thread_intent_eval_cmd.add_argument(
        "--timeout-seconds",
        dest="timeout_seconds",
        type=float,
        default=120.0,
        help=_("cli.analyze.cross_thread_intent_eval.opt.timeout_seconds.help"),
    )

    analyze_cross_thread_memory_recall_cmd = analyze_subparsers.add_parser(
        "cross-thread-memory-recall",
        help=_("cli.analyze.cross_thread_memory_recall.help"),
    )
    analyze_cross_thread_memory_recall_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.cross_thread_memory_recall.opt.input.help"),
    )

    analyze_semantic_topic_cmd = analyze_subparsers.add_parser(
        "semantic-topic",
        help=_("cli.analyze.semantic_topic.help"),
    )
    analyze_semantic_topic_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.semantic_topic.opt.input.help"),
    )
    analyze_semantic_topic_cmd.add_argument(
        "--model",
        required=True,
        help=_("cli.analyze.semantic_topic.opt.model.help"),
    )
    analyze_semantic_topic_cmd.add_argument(
        "--cluster-id",
        dest="cluster_id",
        help=_("cli.analyze.semantic_topic.opt.cluster_id.help"),
    )
    analyze_semantic_topic_cmd.add_argument(
        "--top-clusters",
        dest="top_clusters",
        type=int,
        default=20,
        help=_("cli.analyze.semantic_topic.opt.top_clusters.help"),
    )
    analyze_semantic_topic_cmd.add_argument(
        "--min-cluster-size",
        dest="min_cluster_size",
        type=int,
        default=1,
        help=_("cli.analyze.semantic_topic.opt.min_cluster_size.help"),
    )
    analyze_semantic_topic_cmd.add_argument(
        "--cross-thread-only",
        dest="cross_thread_only",
        action="store_true",
        help=_("cli.analyze.semantic_topic.opt.cross_thread_only.help"),
    )
    analyze_semantic_topic_cmd.add_argument(
        "--base-url",
        dest="base_url",
        default="http://localhost:11434",
        help=_("cli.analyze.semantic_topic.opt.base_url.help"),
    )
    analyze_semantic_topic_cmd.add_argument(
        "--timeout-seconds",
        dest="timeout_seconds",
        type=float,
        default=120.0,
        help=_("cli.analyze.semantic_topic.opt.timeout_seconds.help"),
    )
    analyze_semantic_topic_cmd.add_argument(
        "--state-locale",
        dest="state_locale",
        help=_("cli.analyze.semantic_topic.opt.state_locale.help"),
    )
    analyze_semantic_topic_cmd.add_argument(
        "--json",
        dest="json_output",
        action="store_true",
        help=_("cli.analyze.semantic_topic.opt.json.help"),
    )

    analyze_semantic_topics_cmd = analyze_subparsers.add_parser(
        "semantic-topics",
        help=_("cli.analyze.semantic_topics.help"),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.semantic_topics.opt.input.help"),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--model",
        required=False,
        help=_("cli.analyze.semantic_topics.opt.model.help"),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--cluster-id",
        dest="cluster_id",
        help=_("cli.analyze.semantic_topics.opt.cluster_id.help"),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--min-cluster-size",
        dest="min_cluster_size",
        type=int,
        default=1,
        help=_("cli.analyze.semantic_topics.opt.min_cluster_size.help"),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--cross-thread-only",
        dest="cross_thread_only",
        action=argparse.BooleanOptionalAction,
        default=False,
        help=_("cli.analyze.semantic_topics.opt.cross_thread_only.help"),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--base-url",
        dest="base_url",
        default="http://localhost:11434",
        help=_("cli.analyze.semantic_topics.opt.base_url.help"),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--state-locale",
        dest="state_locale",
        help=_("cli.analyze.semantic_topics.opt.state_locale.help"),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--normalization-job",
        dest="normalization_job",
        help=_("cli.analyze.semantic_topics.opt.normalization_job.help"),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--normalize-representative-spans",
        dest="normalize_representative_spans",
        action="store_true",
        help=_("cli.analyze.semantic_topics.opt.normalize_representative_spans.help"),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--refine-representative-spans-from-proposals",
        dest="refine_representative_spans_from_proposals",
        action="store_true",
        help=_(
            "cli.analyze.semantic_topics.opt.refine_representative_spans_from_proposals.help"
        ),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--expected-taxonomy-version",
        dest="expected_taxonomy_version",
        help=_("cli.analyze.semantic_topics.opt.expected_taxonomy_version.help"),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--strict-normalization",
        dest="strict_normalization",
        action=argparse.BooleanOptionalAction,
        default=False,
        help=_("cli.analyze.semantic_topics.opt.strict_normalization.help"),
    )
    analyze_semantic_topics_cmd.add_argument(
        "--timeout-seconds",
        dest="timeout_seconds",
        type=float,
        default=120.0,
        help=_("cli.analyze.semantic_topics.opt.timeout_seconds.help"),
    )

    analyze_semantic_topic_explore_cmd = analyze_subparsers.add_parser(
        "semantic-topic-explore",
        help=_("cli.analyze.semantic_topic_explore.help"),
    )
    analyze_semantic_topic_explore_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.semantic_topic_explore.opt.input.help"),
    )
    analyze_semantic_topic_explore_cmd.add_argument(
        "--topic-id",
        dest="topic_id",
        help=_("cli.analyze.semantic_topic_explore.opt.topic_id.help"),
    )
    analyze_semantic_topic_explore_cmd.add_argument(
        "--message-id",
        dest="message_id",
        help=_("cli.analyze.semantic_topic_explore.opt.message_id.help"),
    )
    analyze_semantic_topic_explore_cmd.add_argument(
        "--conversation-id",
        "--thread",
        dest="conversation_id",
        help=_("cli.analyze.semantic_topic_explore.opt.conversation_id.help"),
    )
    analyze_semantic_topic_explore_cmd.add_argument(
        "--hide-single-window",
        dest="hide_single_window",
        action="store_true",
        help=_("cli.analyze.semantic_topic_explore.opt.hide_single_window.help"),
    )
    analyze_semantic_topic_explore_cmd.add_argument(
        "--min-window-count",
        dest="min_window_count",
        type=int,
        default=1,
        help=_("cli.analyze.semantic_topic_explore.opt.min_window_count.help"),
    )
    analyze_semantic_topic_explore_cmd.add_argument(
        "--min-conversation-count",
        dest="min_conversation_count",
        type=int,
        default=1,
        help=_("cli.analyze.semantic_topic_explore.opt.min_conversation_count.help"),
    )
    analyze_semantic_topic_explore_cmd.add_argument(
        "--min-displayable-messages",
        dest="min_displayable_messages",
        type=int,
        default=0,
        help=_("cli.analyze.semantic_topic_explore.opt.min_displayable_messages.help"),
    )
    analyze_semantic_topic_explore_cmd.add_argument(
        "--view",
        dest="view",
        action="store_true",
        help=_("cli.analyze.semantic_topic_explore.opt.view.help"),
    )
    analyze_semantic_topic_explore_cmd.add_argument(
        "--full-messages",
        dest="full_messages",
        action="store_true",
        help=_("cli.analyze.semantic_topic_explore.opt.full_messages.help"),
    )
    analyze_semantic_topic_explore_cmd.add_argument(
        "--max-chars",
        dest="max_chars",
        type=int,
        default=400,
        help=_("cli.analyze.semantic_topic_explore.opt.max_chars.help"),
    )
    analyze_semantic_topic_explore_cmd.add_argument(
        "--json",
        dest="json_output",
        action="store_true",
        help=_("cli.analyze.semantic_topic_explore.opt.json.help"),
    )

    analyze_semantic_normalization_cmd = analyze_subparsers.add_parser(
        "semantic-normalization",
        help=_("cli.analyze.semantic_normalization.help"),
    )
    analyze_semantic_normalization_subparsers = (
        analyze_semantic_normalization_cmd.add_subparsers(
            dest="semantic_normalization_command",
            required=True,
        )
    )

    analyze_semantic_normalization_run_cmd = (
        analyze_semantic_normalization_subparsers.add_parser(
            "run",
            help=_("cli.analyze.semantic_normalization.run.help"),
        )
    )
    analyze_semantic_normalization_run_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.semantic_normalization.opt.input.help"),
    )
    analyze_semantic_normalization_run_cmd.add_argument(
        "--job-id",
        dest="job_id",
        help=_("cli.analyze.semantic_normalization.opt.job_id.help"),
    )
    analyze_semantic_normalization_run_cmd.add_argument(
        "--model",
        required=True,
        help=_("cli.analyze.semantic_normalization.opt.model.help"),
    )
    analyze_semantic_normalization_run_cmd.add_argument(
        "--base-url",
        dest="base_url",
        default="http://localhost:11434",
        help=_("cli.analyze.semantic_normalization.opt.base_url.help"),
    )
    analyze_semantic_normalization_run_cmd.add_argument(
        "--timeout-seconds",
        dest="timeout_seconds",
        type=float,
        default=120.0,
        help=_("cli.analyze.semantic_normalization.opt.timeout_seconds.help"),
    )
    analyze_semantic_normalization_run_cmd.add_argument(
        "--temperature",
        type=float,
        default=0.0,
        help=_("cli.analyze.semantic_normalization.opt.temperature.help"),
    )
    analyze_semantic_normalization_run_cmd.add_argument(
        "--raw-num-predict",
        dest="raw_num_predict",
        type=int,
        default=180,
        help=_("cli.analyze.semantic_normalization.opt.raw_num_predict.help"),
    )
    analyze_semantic_normalization_run_cmd.add_argument(
        "--mapping-num-predict",
        dest="mapping_num_predict",
        type=int,
        default=160,
        help=_("cli.analyze.semantic_normalization.opt.mapping_num_predict.help"),
    )
    analyze_semantic_normalization_run_cmd.add_argument(
        "--overwrite",
        dest="overwrite",
        action="store_true",
        help=_("cli.analyze.semantic_normalization.opt.overwrite.help"),
    )

    analyze_semantic_normalization_status_cmd = (
        analyze_semantic_normalization_subparsers.add_parser(
            "status",
            help=_("cli.analyze.semantic_normalization.status.help"),
        )
    )
    analyze_semantic_normalization_status_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.semantic_normalization.opt.input.help"),
    )
    analyze_semantic_normalization_status_cmd.add_argument(
        "--job-id",
        dest="job_id",
        required=True,
        help=_("cli.analyze.semantic_normalization.opt.job_id.help"),
    )
    analyze_semantic_normalization_status_cmd.add_argument(
        "--json",
        dest="json_output",
        action="store_true",
        help=_("cli.analyze.semantic_normalization.opt.json.help"),
    )

    analyze_semantic_normalization_resume_cmd = (
        analyze_semantic_normalization_subparsers.add_parser(
            "resume",
            help=_("cli.analyze.semantic_normalization.resume.help"),
        )
    )
    analyze_semantic_normalization_resume_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.semantic_normalization.opt.input.help"),
    )
    analyze_semantic_normalization_resume_cmd.add_argument(
        "--job-id",
        dest="job_id",
        required=True,
        help=_("cli.analyze.semantic_normalization.opt.job_id.help"),
    )

    analyze_semantic_normalization_retry_cmd = (
        analyze_semantic_normalization_subparsers.add_parser(
            "retry-failures",
            help=_("cli.analyze.semantic_normalization.retry_failures.help"),
        )
    )
    analyze_semantic_normalization_retry_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.semantic_normalization.opt.input.help"),
    )
    analyze_semantic_normalization_retry_cmd.add_argument(
        "--job-id",
        dest="job_id",
        required=True,
        help=_("cli.analyze.semantic_normalization.opt.job_id.help"),
    )
    analyze_semantic_normalization_retry_cmd.add_argument(
        "--span-id",
        dest="span_ids",
        action="append",
        help=_("cli.analyze.semantic_normalization.opt.span_id.help"),
    )
    analyze_semantic_normalization_retry_cmd.add_argument(
        "--limit",
        dest="limit",
        type=int,
        help=_("cli.analyze.semantic_normalization.opt.limit.help"),
    )

    analyze_semantic_normalization_summary_cmd = (
        analyze_semantic_normalization_subparsers.add_parser(
            "summary",
            help=_("cli.analyze.semantic_normalization.summary.help"),
        )
    )
    analyze_semantic_normalization_summary_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.semantic_normalization.opt.input.help"),
    )
    analyze_semantic_normalization_summary_cmd.add_argument(
        "--job-id",
        dest="job_id",
        required=True,
        help=_("cli.analyze.semantic_normalization.opt.job_id.help"),
    )
    analyze_semantic_normalization_summary_cmd.add_argument(
        "--json",
        dest="json_output",
        action="store_true",
        help=_("cli.analyze.semantic_normalization.opt.json.help"),
    )

    analyze_semantic_normalization_compare_cmd = (
        analyze_semantic_normalization_subparsers.add_parser(
            "compare",
            help=_("cli.analyze.semantic_normalization.compare.help"),
        )
    )
    analyze_semantic_normalization_compare_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.analyze.semantic_normalization.opt.input.help"),
    )
    analyze_semantic_normalization_compare_cmd.add_argument(
        "--job-a",
        dest="job_a",
        required=True,
        help=_("cli.analyze.semantic_normalization.opt.job_a.help"),
    )
    analyze_semantic_normalization_compare_cmd.add_argument(
        "--job-b",
        dest="job_b",
        required=True,
        help=_("cli.analyze.semantic_normalization.opt.job_b.help"),
    )
    analyze_semantic_normalization_compare_cmd.add_argument(
        "--json",
        dest="json_output",
        action="store_true",
        help=_("cli.analyze.semantic_normalization.opt.json.help"),
    )

    chain_cmd = subparsers.add_parser(
        "chain",
        help=_("cli.chain.help"),
    )
    chain_cmd.add_argument(
        "--provider",
        required=False,
        help=_("cli.parse.opt.provider.help"),
    )
    chain_cmd.add_argument(
        "--dry-run",
        dest="dry_run",
        action="store_true",
        help=_("cli.parse.opt.dry_run.help"),
    )
    chain_cmd.add_argument(
        "--input",
        required=False,
        type=Path,
        help=_("cli.chain.opt.input.help"),
    )
    chain_cmd.add_argument(
        "--outdir",
        required=False,
        type=Path,
        default=Path("artifacts"),
        help=_("cli.chain.opt.outdir.help"),
    )
    chain_cmd.add_argument(
        "--timezone",
        "--tz",
        dest="timezone",
        required=False,
        default="UTC",
        help=_("cli.option.timezone.help"),
    )
    chain_cmd.add_argument(
        "--formatting",
        choices=["none", "light"],
        default="light",
        help=_("cli.option.formatting.help"),
    )
    chain_cmd.add_argument("--split", dest="split", help=_("cli.option.split.help"))
    chain_cmd.add_argument("--split-soft-overflow", dest="split_soft_overflow", type=float, default=0.20)
    chain_cmd.add_argument("--split-hard", dest="split_hard", action="store_true")
    chain_cmd.add_argument("--split-preview", dest="split_preview", action="store_true")
    chain_cmd.add_argument(
        "--tiny-tail-threshold",
        dest="tiny_tail_threshold",
        type=int,
        default=20,
        help=_("cli.option.tiny_tail_threshold.help"),
    )
    chain_cmd.add_argument(
        "--export-outdir",
        dest="export_outdir",
        type=Path,
        help=_("cli.chain.opt.export_outdir.help"),
    )
    chain_cmd.add_argument(
        "--parsed-root",
        dest="parsed_root",
        type=Path,
        help=_("cli.chain.opt.parsed_root.help"),
    )
    chain_cmd.add_argument(
        "--fail-fast",
        dest="fail_fast",
        action="store_true",
        help=_("cli.chain.opt.fail_fast.help"),
    )
    chain_cmd.add_argument(
        "--validate-schema",
        dest="validate_schema",
        action="store_true",
        help=_("cli.chain.opt.validate_schema.help"),
    )
    chain_cmd.add_argument(
        "--message-window-size",
        dest="message_window_size",
        type=int,
        default=4,
        help=_("cli.chain.opt.message_window_size.help"),
    )
    chain_cmd.add_argument(
        "--message-window-stride",
        dest="message_window_stride",
        type=int,
        default=None,
        help=_("cli.chain.opt.message_window_stride.help"),
    )

    subparsers.add_parser("viewer", help=_("cli.viewer.help"))

    config_cmd = subparsers.add_parser(
        "config",
        help=_("cli.config.help"),
    )
    config_subparsers = config_cmd.add_subparsers(
        dest="config_command",
        required=True,
    )
    config_subparsers.add_parser("path", help=_("cli.config.path.help"))
    config_subparsers.add_parser("show", help=_("cli.config.show.help"))
    config_subparsers.add_parser("validate", help=_("cli.config.validate.help"))

    lexical_cmd = subparsers.add_parser(
        "lexical",
        help=_("cli.lexical.help"),
        description=_("cli.lexical.help"),
    )
    lexical_subparsers = lexical_cmd.add_subparsers(
        dest="lexical_command",
        required=True,
    )
    lexical_policy_cmd = lexical_subparsers.add_parser(
        "policy",
        help=_("cli.lexical.policy.help"),
        description=_("cli.lexical.policy.help"),
    )
    lexical_policy_subparsers = lexical_policy_cmd.add_subparsers(
        dest="lexical_policy_command",
        required=True,
    )
    lexical_policy_validate_cmd = lexical_policy_subparsers.add_parser(
        "validate",
        help=_("cli.lexical.policy.validate.help"),
        description=_("cli.lexical.policy.validate.help"),
    )
    lexical_policy_validate_cmd.add_argument(
        "--project-lexical-rules",
        dest="project_lexical_rules",
        type=Path,
        default=None,
        help=_("cli.lexical.policy.opt.project_lexical_rules.help"),
    )
    lexical_policy_validate_cmd.add_argument(
        "--user-lexical-rules",
        dest="user_lexical_rules",
        type=Path,
        default=None,
        help=_("cli.lexical.policy.opt.user_lexical_rules.help"),
    )
    lexical_policy_validate_cmd.add_argument(
        "--json",
        dest="json_output",
        action="store_true",
        help=_("cli.analyze.opt.json.help"),
    )
    lexical_policy_validate_cmd.add_argument(
        "--out",
        required=False,
        type=Path,
        help=_("cli.analyze.opt.out.help"),
    )
    lexical_policy_resolve_cmd = lexical_policy_subparsers.add_parser(
        "resolve",
        help=_("cli.lexical.policy.resolve.help"),
        description=_("cli.lexical.policy.resolve.help"),
    )
    lexical_policy_resolve_cmd.add_argument(
        "--locale",
        dest="policy_locale",
        default=None,
        help=_("cli.lexical.policy.opt.locale.help"),
    )
    lexical_policy_resolve_cmd.add_argument(
        "--project-lexical-rules",
        dest="project_lexical_rules",
        type=Path,
        default=None,
        help=_("cli.lexical.policy.opt.project_lexical_rules.help"),
    )
    lexical_policy_resolve_cmd.add_argument(
        "--user-lexical-rules",
        dest="user_lexical_rules",
        type=Path,
        default=None,
        help=_("cli.lexical.policy.opt.user_lexical_rules.help"),
    )
    lexical_policy_resolve_cmd.add_argument(
        "--json",
        dest="json_output",
        action="store_true",
        help=_("cli.analyze.opt.json.help"),
    )
    lexical_policy_resolve_cmd.add_argument(
        "--out",
        required=False,
        type=Path,
        help=_("cli.analyze.opt.out.help"),
    )

    return parser
